# Playbook to configure a Respian-based Raspberry PI to support the MPR121 Capacative Touch HAT
---
- hosts: all
  remote_user: pi
  become: true
  become_method: sudo

  tasks:
    - name: Install required packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - python3-pip
        - python-pygame
        - build-essential
        - python-dev
        - python-smbus
      become: true
      become_method: sudo

    - name: Checkout the Adafruit MPR121 Repo from Github
      git:
        repo: https://github.com/adafruit/Adafruit_Python_MPR121.git
        dest: /home/pi/cap-touch
      remote_user: pi

    - name: Install required Python packages
      pip:
        name: Adafruit-GPIO

    - name: Reboot the Raspberry Pi
      command: /sbin/reboot