# Playbook to configure a Respian-based Raspberry PI to support the MPR121 Capacative Touch HAT
---
- hosts: all
  remote_user: pi


  tasks:
    - name: Enable the I2C Interface
      block:
        - replace:
            path: /boot/config.txt
            regexp: '#dtparam=i2c_arm=on'
            replace: 'dtparam=i2c_arm=on'
          become: true
          become_method: sudo

      # See https://learn.adafruit.com/mpr121-capacitive-touch-sensor-on-raspberry-pi-and-beaglebone-black/software for detail
        - blockinfile:
            path: /boot/config.txt
            block: |
              dtoverlay=i2c-bcm2708
            become: true
            become_method: sudo

    - name: Install required packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - python3-pip
        - python-pygame
        - build-essential
        - python-dev
        - python-smbus
      become: true
      become_method: sudo

    - name: Checkout the Adafruit MPR121 Repo from Github
      git:
        repo: https://github.com/adafruit/Adafruit_Python_MPR121.git
        dest: /home/pi/cap-touch

    - name: Install required Python packages
      command: python /home/pi/cap-touch setup.py install
      become: true
      become_method: sudo

    - name: Reboot the Raspberry Pi to enable system-level changes
      command: /sbin/reboot